# zh/en
language: zh

# 最大记录数量
# Maximum number of records
max-records: 1

# 设置为true开启调试模式，控制台会输出监听到的命令
# Set to true to enable debugging mode, the console will output the commands it listens to
debug-mode: false

# 是否启用来回back模式，启用后玩家可以在两个位置之间来回传送
#Is the back and forth mode enabled? Once enabled, players can teleport back and forth between two positions
toggle-back-mode: true

# 需要监听的传送类命令
# Transmission commands that need to be monitored.
tracked-commands:
  - "cmi home"
  - "cmi warp"
  - "res tp" # 匹配/res tp开头的所有命令 / Match all commands starting with /res tp
  - "teleport"
  - "tp"