# zh/en
language: zh

# 最大记录数量#
# Maximum number of records
max-records: 2

# 需要监听的传送类命令
# Transmission commands that need to be monitored.
tracked-commands:
  - /tp
  - /res tp
  - /home
  - /warp