name: Simpleback
version: '1.1'
main: cn.kurt6.back.Simpleback
api-version: 1.16
author: Kurt
folia-supported: true
commands:
  back:
    description: 传送回上一个记录点
    usage: /back

permissions:
  simpleback.back:
    description: 允许使用/back命令
    default: true